export const areaList = [
  { name: 'Afghanistan', alias: 'AF' },
  { name: 'Aland Islands', alias: 'AX' },
  { name: 'Albania', alias: 'AL' },
  { name: 'Algeria', alias: 'DZ' },
  { name: 'American Samoa', alias: 'AS' },
  { name: 'Andorra', alias: 'AD' },
  { name: 'Angola', alias: 'AO' },
  { name: 'Anguilla', alias: 'AI' },
  { name: 'Antarctica', alias: 'AQ' },
  { name: 'Antigua and Barbuda', alias: 'AG' },
  { name: 'Argentina', alias: 'AR' },
  { name: 'Armenia', alias: 'AM' },
  { name: 'Aruba', alias: 'AW' },
  { name: 'Australia', alias: 'AU' },
  { name: 'Austria', alias: 'AT' },
  { name: 'Azerbaijan', alias: 'AZ' },
  { name: 'Bahamas', alias: 'BS' },
  { name: 'Bahrain', alias: 'BH' },
  { name: 'Bangladesh', alias: 'BD' },
  { name: 'Barbados', alias: 'BB' },
  { name: 'Belarus', alias: 'BY' },
  { name: 'Belgium', alias: 'BE' },
  { name: 'Belize', alias: 'BZ' },
  { name: 'Benin', alias: 'BJ' },
  { name: 'Bermuda', alias: 'BM' },
  { name: 'Bhutan', alias: 'BT' },
  { name: 'Bolivia', alias: 'BO' },
  { name: 'Bosnia and Herzegovina', alias: 'BA' },
  { name: 'Botswana', alias: 'BW' },
  { name: 'Bouvet Island', alias: 'BV' },
  { name: 'Brazil', alias: 'BR' },
  { name: 'British Indian Ocean Territory', alias: 'IO' },
  { name: 'Brunei', alias: 'BN' },
  { name: 'Bulgaria', alias: 'BG' },
  { name: 'Burkina Faso', alias: 'BF' },
  { name: 'Burma (Myanmar)', alias: 'MM' },
  { name: 'Burundi', alias: 'BI' },
  { name: 'Cambodia', alias: 'KH' },
  { name: 'Cameroon', alias: 'CM' },
  { name: 'Canada', alias: 'CA' },
  { name: 'Cape Verde', alias: 'CV' },
  { name: 'Cayman Islands', alias: 'KY' },
  { name: 'Central African Republic', alias: 'CF' },
  { name: 'Chad', alias: 'TD' },
  { name: 'Chile', alias: 'CL' },
  { name: 'China', alias: 'CN' },
  { name: 'Christmas Island', alias: 'CX' },
  { name: 'Cocos (Keeling) Islands', alias: 'CC' },
  { name: 'Colombia', alias: 'CO' },
  { name: 'Comoros', alias: 'KM' },
  { name: 'Congo, Dem. Republic', alias: 'CD' },
  { name: 'Congo, Republic', alias: 'CG' },
  { name: 'Cook Islands', alias: 'CK' },
  { name: 'Costa Rica', alias: 'CR' },
  { name: 'Croatia', alias: 'HR' },
  { name: 'Cuba', alias: 'CU' },
  { name: 'Cyprus', alias: 'CY' },
  { name: 'Czech Republic', alias: 'CZ' },
  { name: 'Denmark', alias: 'DK' },
  { name: 'Djibouti', alias: 'DJ' },
  { name: 'Dominica', alias: 'DM' },
  { name: 'Dominican Republic', alias: 'DO' },
  { name: 'East Timor', alias: 'TL' },
  { name: 'Ecuador', alias: 'EC' },
  { name: 'Egypt', alias: 'EG' },
  { name: 'El Salvador', alias: 'SV' },
  { name: 'Equatorial Guinea', alias: 'GQ' },
  { name: 'Eritrea', alias: 'ER' },
  { name: 'Estonia', alias: 'EE' },
  { name: 'Ethiopia', alias: 'ET' },
  { name: 'Falkland Islands', alias: 'FK' },
  { name: 'Faroe Islands', alias: 'FO' },
  { name: 'Fiji', alias: 'FJ' },
  { name: 'Finland', alias: 'FI' },
  { name: 'France', alias: 'FR' },
  { name: 'French Guiana', alias: 'GF' },
  { name: 'French Polynesia', alias: 'PF' },
  { name: 'French Southern Territories', alias: 'TF' },
  { name: 'Gabon', alias: 'GA' },
  { name: 'Gambia', alias: 'GM' },
  { name: 'Georgia', alias: 'GE' },
  { name: 'Germany', alias: 'DE' },
  { name: 'Ghana', alias: 'GH' },
  { name: 'Gibraltar', alias: 'GI' },
  { name: 'Greece', alias: 'GR' },
  { name: 'Greenland', alias: 'GL' },
  { name: 'Grenada', alias: 'GD' },
  { name: 'Guadeloupe', alias: 'GP' },
  { name: 'Guam', alias: 'GU' },
  { name: 'Guatemala', alias: 'GT' },
  { name: 'Guernsey', alias: 'GG' },
  { name: 'Guinea', alias: 'GN' },
  { name: 'Guinea-Bissau', alias: 'GW' },
  { name: 'Guyana', alias: 'GY' },
  { name: 'Haiti', alias: 'HT' },
  { name: 'Heard Island and McDonald Islands', alias: 'HM' },
  { name: 'Honduras', alias: 'HN' },
  { name: 'HongKong', alias: 'HK' },
  { name: 'Hungary', alias: 'HU' },
  { name: 'Iceland', alias: 'IS' },
  { name: 'India', alias: 'IN' },
  { name: 'Indonesia', alias: 'ID' },
  { name: 'Iran', alias: 'IR' },
  { name: 'Iraq', alias: 'IQ' },
  { name: 'Ireland', alias: 'IE' },
  { name: 'Israel', alias: 'IL' },
  { name: 'Italy', alias: 'IT' },
  { name: 'Ivory Coast', alias: 'CI' },
  { name: 'Jamaica', alias: 'JM' },
  { name: 'Japan', alias: 'JP' },
  { name: 'Jersey', alias: 'JE' },
  { name: 'Jordan', alias: 'JO' },
  { name: 'Kazakhstan', alias: 'KZ' },
  { name: 'Kenya', alias: 'KE' },
  { name: 'Kiribati', alias: 'KI' },
  { name: 'Korea, Dem. Republic of', alias: 'KP' },
  { name: 'Kuwait', alias: 'KW' },
  { name: 'Kyrgyzstan', alias: 'KG' },
  { name: 'Laos', alias: 'LA' },
  { name: 'Latvia', alias: 'LV' },
  { name: 'Lebanon', alias: 'LB' },
  { name: 'Lesotho', alias: 'LS' },
  { name: 'Liberia', alias: 'LR' },
  { name: 'Libya', alias: 'LY' },
  { name: 'Liechtenstein', alias: 'LI' },
  { name: 'Lithuania', alias: 'LT' },
  { name: 'Luxemburg', alias: 'LU' },
  { name: 'Macau', alias: 'MO' },
  { name: 'Macedonia', alias: 'MK' },
  { name: 'Madagascar', alias: 'MG' },
  { name: 'Malawi', alias: 'MW' },
  { name: 'Malaysia', alias: 'MY' },
  { name: 'Maldives', alias: 'MV' },
  { name: 'Mali', alias: 'ML' },
  { name: 'Malta', alias: 'MT' },
  { name: 'Man Island', alias: 'IM' },
  { name: 'Marshall Islands', alias: 'MH' },
  { name: 'Martinique', alias: 'MQ' },
  { name: 'Mauritania', alias: 'MR' },
  { name: 'Mauritius', alias: 'MU' },
  { name: 'Mayotte', alias: 'YT' },
  { name: 'Mexico', alias: 'MX' },
  { name: 'Micronesia', alias: 'FM' },
  { name: 'Moldova', alias: 'MD' },
  { name: 'Monaco', alias: 'MC' },
  { name: 'Mongolia', alias: 'MN' },
  { name: 'Montenegro', alias: 'ME' },
  { name: 'Montserrat', alias: 'MS' },
  { name: 'Morocco', alias: 'MA' },
  { name: 'Mozambique', alias: 'MZ' },
  { name: 'Namibia', alias: 'NA' },
  { name: 'Nauru', alias: 'NR' },
  { name: 'Nepal', alias: 'NP' },
  { name: 'Netherlands', alias: 'NL' },
  { name: 'Netherlands Antilles', alias: 'AN' },
  { name: 'New Caledonia', alias: 'NC' },
  { name: 'New Zealand', alias: 'NZ' },
  { name: 'Nicaragua', alias: 'NI' },
  { name: 'Niger', alias: 'NE' },
  { name: 'Nigeria', alias: 'NG' },
  { name: 'Niue', alias: 'NU' },
  { name: 'Norfolk Island', alias: 'NF' },
  { name: 'Northern Mariana Islands', alias: 'MP' },
  { name: 'Norway', alias: 'NO' },
  { name: 'Oman', alias: 'OM' },
  { name: 'Pakistan', alias: 'PK' },
  { name: 'Palau', alias: 'PW' },
  { name: 'Palestinian Territories', alias: 'PS' },
  { name: 'Panama', alias: 'PA' },
  { name: 'Papua New Guinea', alias: 'PG' },
  { name: 'Paraguay', alias: 'PY' },
  { name: 'Peru', alias: 'PE' },
  { name: 'Philippines', alias: 'PH' },
  { name: 'Pitcairn', alias: 'PN' },
  { name: 'Poland', alias: 'PL' },
  { name: 'Portugal', alias: 'PT' },
  { name: 'Puerto Rico', alias: 'PR' },
  { name: 'Qatar', alias: 'QA' },
  { name: 'Reunion Island', alias: 'RE' },
  { name: 'Romania', alias: 'RO' },
  { name: 'Russian Federation', alias: 'RU' },
  { name: 'Rwanda', alias: 'RW' },
  { name: 'Saint Barthelemy', alias: 'BL' },
  { name: 'Saint Kitts and Nevis', alias: 'KN' },
  { name: 'Saint Lucia', alias: 'LC' },
  { name: 'Saint Martin', alias: 'MF' },
  { name: 'Saint Pierre and Miquelon', alias: 'PM' },
  { name: 'Saint Vincent and the Grenadines', alias: 'VC' },
  { name: 'Samoa', alias: 'WS' },
  { name: 'San Marino', alias: 'SM' },
  { name: 'Saudi Arabia', alias: 'SA' },
  { name: 'Senegal', alias: 'SN' },
  { name: 'Serbia', alias: 'RS' },
  { name: 'Seychelles', alias: 'SC' },
  { name: 'Sierra Leone', alias: 'SL' },
  { name: 'Singapore', alias: 'SG' },
  { name: 'Slovakia', alias: 'SK' },
  { name: 'Slovenia', alias: 'SI' },
  { name: 'Solomon Islands', alias: 'SB' },
  { name: 'Somalia', alias: 'SO' },
  { name: 'South Africa', alias: 'ZA' },
  { name: 'South Georgia and the South Sandwich Islands', alias: 'GS' },
  { name: 'South Korea', alias: 'KR' },
  { name: 'Spain', alias: 'ES' },
  { name: 'Sri Lanka', alias: 'LK' },
  { name: 'Sudan', alias: 'SD' },
  { name: 'Suriname', alias: 'SR' },
  { name: 'Svalbard and Jan Mayen', alias: 'SJ' },
  { name: 'Swaziland', alias: 'SZ' },
  { name: 'Sweden', alias: 'SE' },
  { name: 'Switzerland', alias: 'CH' },
  { name: 'Syria', alias: 'SY' },
  { name: 'São Tomé and Príncipe', alias: 'ST' },
  { name: 'Taiwan', alias: 'TW' },
  { name: 'Tajikistan', alias: 'TJ' },
  { name: 'Tanzania', alias: 'TZ' },
  { name: 'Thailand', alias: 'TH' },
  { name: 'Togo', alias: 'TG' },
  { name: 'Tokelau', alias: 'TK' },
  { name: 'Tonga', alias: 'TO' },
  { name: 'Trinidad and Tobago', alias: 'TT' },
  { name: 'Tunisia', alias: 'TN' },
  { name: 'Turkey', alias: 'TR' },
  { name: 'Turkmenistan', alias: 'TM' },
  { name: 'Turks and Caicos Islands', alias: 'TC' },
  { name: 'Tuvalu', alias: 'TV' },
  { name: 'Uganda', alias: 'UG' },
  { name: 'Ukraine', alias: 'UA' },
  { name: 'United Arab Emirates', alias: 'AE' },
  { name: 'United Kingdom', alias: 'GB' },
  { name: 'United States', alias: 'US' },
  { name: 'Uruguay', alias: 'UY' },
  { name: 'Uzbekistan', alias: 'UZ' },
  { name: 'Vanuatu', alias: 'VU' },
  { name: 'Vatican City State', alias: 'VA' },
  { name: 'Venezuela', alias: 'VE' },
  { name: 'Vietnam', alias: 'VN' },
  { name: 'Virgin Islands (British)', alias: 'VG' },
  { name: 'Virgin Islands (U.S.)', alias: 'VI' },
  { name: 'Wallis and Futuna', alias: 'WF' },
  { name: 'Western Sahara', alias: 'EH' },
  { name: 'Yemen', alias: 'YE' },
  { name: 'Zambia', alias: 'ZM' },
  { name: 'Zimbabwe', alias: 'ZW' }
]
